alias pof='sudo poweroff now'
alias adom='~/Installed/adom/adom'
alias cstrike='~/Scripts/cstrike.sh'
alias wp='~/Scripts/wallpapers.sh'
alias open='xdg-open'
alias cod='cd ~/Documents/Coded'
alias wor='cd ~/Documents/Work'
alias ayy='figlet lmao -t -c -f big'
alias t='~/Scripts/time.sh'
alias m='~/Scripts/matrix.sh'
alias e='exit'
alias secret='encfs -i 5 ~/.Private/ ~/Private'
alias cd..='cd ..'
alias show='~/Scripts/cacaview.sh'
alias ды='ls'
alias mem_free='sudo sysctl -w vm.drop_caches=3'
